kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .RoleAndRolebindingName }}
  namespace: {{ .ClusterName }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["managedclusteraddons"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["managedclusteraddons/status"]
    verbs: ["patch", "update"]
