kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .RoleAndRolebindingName }}
  namespace: {{ .ClusterName }}
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["managedclusteraddons"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["addon.open-cluster-management.io"]
    resources: ["managedclusteraddons/status"]
    verbs: ["patch", "update"]
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["addonplacementscores", "addonplacementscores/status"]
    verbs: ["get", "list", "watch", "create", "delete", "update", patch]
  - apiGroups: [ "discovery.open-cluster-management.io" ]
    resources: [ "discoveredclusters" ]
    verbs: [ "get", "list", "watch", "create", "update", "delete", "deletecollection", "patch" ]